# Site Settings
title:               Nazmi Aydın
tagline:             #a minimalist Jekyll theme
description:
baseurl:            #"/"
url:                "https://nazmiaydin.github.io"
github:
  url:               #"http://github.com/nazmiaydin/"
author:
  name:              "Nazmi Aydın"
  email:             "nazmiaydin034@gmail.com"
  twitter:           #"paululele"
  instagram:         #"paululele"
  github:            "nazmiaydin"
  facebook:          #"Le.Paul.94"
  linkedin:          #"lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
